### ISSUE TITLE
week 05 - day 02 - favorite music

### ISSUE THREAD

**Issue by mdewey** [AllanHall/assignments#18]
# Music Madness

For tonight, I want you to show off your music artists. You will be creating a multiple page app, using react-router.

## Objectives

- Create a SPA, with a few pages
- Deploying your website

## Requirements

- Build a website that has 4 pages.
  - 1 landing
  - a page for your top three favorite bands.

### Explorer Mode

- [x] Add `react-router-dom` to your project.
- [x] Create a Landing page that displays a short description of all three of your bands
- [x] Build 3 band pages. These pages should have a
  - [x] a band picture
  - [x] band name
  - [x] Latest Album information
- [x] Each page should have a nav bar that allows the user to browse from page to page
- [x] Deploy your site

_TIP_: for Explorer mode focus on getting the router set up and linking the pages to each other.

### Adventure Mode

- [ ] Instead of hard coding the URL, try to use parameters, components and JSON file to supply navigation for your site.

### Epic Mode

- [ ] Add integrations from [Last.fm API](https://www.last.fm/api). This API has a bunch of features. Go crazy, the sky is the limit.

## Additional Resources

- [npm react-router-dom](https://www.npmjs.com/package/react-router-dom)
- `yarn add react-router-dom`

**Comment by AllanHall** [comment]
https://github.com/AllanHall/artists.git
only finished explorer mode, kinda went crazy with the css.
really happy with the overall look of the page though

**Comment by mdewey** [comment]
Your homework was marked: **Exceeds Expectations**

![Gavin Approved!](https://gifs.suncoast.io/rails/active_storage/blobs/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBCZz09IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--cd97f19100495726ff64a3d09a685c898b2e76b3/gavin-lol.gif)
> &ldquo;Gavin Approved!&rdquo;
__&mdash; via **[Jason L Perry](https://gifs.suncoast.io/venerations/1)**__
