### ISSUE TITLE
 capstone 01 - One little spark

### ISSUE THREAD

**Issue by mdewey** [AllanHall/assignments#25]
# It starts with a plan.

We are starting the final stretch of the cohort. This means we are starting to focus on our capstone projects.

## What is a capstone project

The capstone project is the final of the course. This project should be significant in scope, but able to be trimmed down to a [MVP (minimal viable product)](https://www.freecodecamp.org/news/what-the-hell-does-minimum-viable-product-actually-mean-anyway-7d8f6a110f38/). Capstones are not necessarily new ideas that are supposed to change the world. Even though your ideas are accepted (and sometimes encourage, with instructor guidance), some of the best demo's did re-invent the wheel.

The capstone has 2 mains goals.

- The capstone provides you _practice_ on the skills that you have grown over the course. During the course, you have built many projects, but on a small scale. The capstone projects allow you to built something at a bigger scale, and over a longer timeline. This more significant scope helps reinforce fundamental concepts.

- The capstone provides a vehicle to _show off_ the skills you have cultivated and want to grow upon further. This project is a great portfolio piece. As described in career support, employers love to see what you build. This portfolio piece helps showcase the skills you want to work on and grow on going forward.

## One little spark. 

As always, when we go to start a new project. The first step is to create an elevator pitch. This is a short description that describes what your final project is doing. This should be similar to what you said during pitches. This provides us with a starting point and guiding star during our project. This elevator pitch should include 

- The problem it solves.
- The core 3 features.

The second step is to always plan out what we are doing. These early plans often take the shape of wireframes. This means that our first task for the capstone projects is to create our wireframes.

The elevator pitch and wireframes should be treated as a detailed road map. When these are created, these should be treated as law; it can be changed but must be changed with purpose.

## Objectives

- Finalize the idea for your capstone
- Create wireframes for your capstone project
- Using `app-app` to start implementing your HTML

## Requirements

- Using your favorite way to create wireframes (paper, whiteboard, website), create all the pages for your site no matter how simple the pages are.
- Create a new repository for your capstone project

### Explorer Mode

- [x] get your project approved by your instructor.

- [x] Create the elevator pitch for your final projects.
- [x] Place this in the `README.md` of your capstone project repository

- [x] Create a wireframe for each page in your page you capstone.
- [x] Place these wireframes in a  `.idea` folder of your capstone project repository.

## Additional Resources

- [Adobe XD](https://www.adobe.com/products/xd.html)
- [Moqups](https://moqups.com/)
- [Figma](https://www.figma.com/)

**Comment by AllanHall** [comment]
https://github.com/AllanHall/travelingo.git

**Comment by mdewey** [comment]
Your homework was marked: **Meets Expectations**

![Ring that bell!](https://gifs.suncoast.io/rails/active_storage/blobs/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBTQT09IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--fabcecd7c921cc4014bfcce0bd127f9e89ef3986/meets-2.gif)
> &ldquo;Ring that bell!&rdquo;
__&mdash; via **[Mark Dewey](https://gifs.suncoast.io/venerations/62)**__
