### ISSUE TITLE
week 08 - day 01 - explosive api

### ISSUE THREAD

**Issue by mdewey** [AllanHall/assignments#30]
# Explosion Api

You have already solved the `explosion` and `mumbling` katas. The client loves your solution so much that they want you to turn it into an API us on the web.

For tonight, I want you to create a simple API with two endpoints, one for the `explosion` and one for the `mumbling`.

## Objectives

- Create a simple API
- Practice problem solving

## Requirements

- Install the `sdg-api` template using the command `dotnet new -i SDG.templates.Web.API`
- Create 2 endpoints, `/api/mumbling` and `api/explosion`, that are based off of the katas,`[https://www.codewars.com/kata/mumbling](https://www.codewars.com/kata/mumbling)` and `[https://www.codewars.com/kata/digits-explosion](https://www.codewars.com/kata/digits-explosion)` respectfully.

### Explorer Mode

- [x] Create a new `sdg-web` api project
- [x] Create a endpoint for the `mumbling` endpoint
  - [x] Create a new Controller called `MumblingController`
  - [x] This will have one `HttpGet`
  - [x] The one get will accept a string
  - [x] This endpoint will take the string passed to it, manipulate according to the kata [https://www.codewars.com/kata/mumbling](https://www.codewars.com/kata/mumbling) and return the result
  - [x] This will return a `ActionResult<string>`
- [x] Create a endpoint for the `explosion` endpoint
  - [x] Create a new Controller called `ExplosionController`
  - [x] This will have one `HttpGet`
  - [x] The one get will accept a string
  - [x] This endpoint will take the string passed to it, manipulate according to the kata [hhttps://www.codewars.com/kata/digits-explosion](hhttps://www.codewars.com/kata/digits-explosion) and return the result
  - [x] This will return a `ActionResult<string>`
- [x] turn in your project via github with a .gitignore.

### Adventure Mode

- [x] Ensure your instructor has seen and approved your wireframes for your capstone.
- [ ] Work on the HTML for your capstone.
- [ ] Work on your Resume for Career Support.

**Comment by AllanHall** [comment]
https://github.com/AllanHall/digitsApi.git

**Comment by mdewey** [comment]
Your homework was marked: **Meets Expectations**

![Ring that bell!](https://gifs.suncoast.io/rails/active_storage/blobs/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBTQT09IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--fabcecd7c921cc4014bfcce0bd127f9e89ef3986/meets-2.gif)
> &ldquo;Ring that bell!&rdquo;
__&mdash; via **[Mark Dewey](https://gifs.suncoast.io/venerations/62)**__
