### ISSUE TITLE
week 08 - day 02 & 03 - inventory api

### ISSUE THREAD

**Issue by mdewey** [AllanHall/assignments#32]
# Don't lose track!

Now that we have new API skills, we want to create an API to help our favorite store keep track of their inventory. This API will be able to let users add, update, delete, and search for items.

## Objectives

- Create an API that can CRUD against a Database
- practice creating ASP.NET Web API endpoints
- practice EF Core.

## Requirements

- Create a simple API that has a handful of endpoints to manage data
- The API should be using Web API Controllers, Ef Core, and Postgres database

### Explorer Mode

- [x] Create a new `sdg-api` project using the dotnet CLI, have fun with the name and what items the shop sells.
- [x] Create a Model of for an item in the shop. This will be your database table structure.
- [x] The Item should have at least

  - [x] Id
  - [x] SKU
  - [x] Name
  - [x] Short description
  - [x] NumberInStock
  - [x] Price
  - [x] DateOrdered

- [x] Create a GET endpoint for all items in your inventory
- [x] Create a GET endpoint for each item
- [x] Create a POST endpoint that allows a user/client to add an item to the inventory
- [x] Create a PUT endpoint that allows a user/client to update an item
- [x] Create a DELETE endpoint that allows a user/client to delete an item
- [x] Create a GET endpoint to get all items that are out of stock
- [x] Create a GET endpoint that allows the user to search for an item based on SKU

### Adventure Mode

- [x] Ensure your instructor has seen and approved your wireframes for your capstone.
- [x] Work on the HTML for your capstone.
- [x] Work on your Resume for Career Support.

**Comment by AllanHall** [comment]
https://github.com/AllanHall/jewelryApi.git

**Comment by mdewey** [comment]
Your homework was marked: **Meets Expectations**

![Ring that bell!](https://gifs.suncoast.io/rails/active_storage/blobs/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBTQT09IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--fabcecd7c921cc4014bfcce0bd127f9e89ef3986/meets-2.gif)
> &ldquo;Ring that bell!&rdquo;
__&mdash; via **[Mark Dewey](https://gifs.suncoast.io/venerations/62)**__
