### ISSUE TITLE
week 09 - day 02 - suncoast overflow

### ISSUE THREAD

**Issue by mdewey** [AllanHall/assignments#35]
# Suncoast Overflow

As we explore the concepts of a full stack web app, a good way to practice is to duplicate an existing site. For this project, you will be creating a copy of a site that you know very well, StackOverflow.

The finished product will be due Friday, so this will be a little bigger. Pace yourself

First, we need to the database schema and start to build the API for the core functionality

## Objectives

- Create a full stack web app, from database to API, to frontend, as well as styled
- Practice working in groups

## Requirements

In groups of 2 or 3, create an anonymous question and answer site, that allows users to up-vote and down-vote questions and answers.

The core functionality is:

- [x] as a user I should be able to view and search questions asked
- [x] As a user I should be able to view a question and its answers
- [x] As a user I should be able to post a question, this can anonymous, and should be for Explorer Mode
- [ ] As a user I should be able to answer a question
- [ ] As a user I should be able to up/down vote an answer
- [ ] As a user I should be able to up/down vote a question

### Explorer Mode

- [x] Create an ERD for the core functionality above
- [x] Create API definitions for all the endpoints needed. This should include URLs, params, body, and return types.
- [x] Create an API that supports your design
- [x] Create the Client app application that uses your API

### Adventure Mode

- [ ] Work on your capstone project

**Comment by AllanHall** [comment]
https://github.com/AllanHall/JohnDoeOverflow.git
got search bar, post a question, and view a question and its answers to work. Didn't get the upvote/downvote to work or our post a question to work yet.

**Comment by mdewey** [comment]
Your homework was marked: **Meets Expectations**

![Great job!](https://gifs.suncoast.io/rails/active_storage/blobs/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBJdz09IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--8167037ff2098b5e812290b56d35e1113c17439d/giphy-downsized.gif)
> &ldquo;Great job!&rdquo;
__&mdash; via **[Jason L Perry](https://gifs.suncoast.io/venerations/24)**__
